=== AggerChen/XMLTest/src/com/agger/XMLTest/dtd/doctor.dtd
<!ELEMENT doctors (doctor*) >
<!ELEMENT doctor (name,age,sex) >
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ATTLIST doctor id ID #REQUIRED>

=== AggerChen/XMLTest/target/classes/com/agger/XMLTest/dtd/doctor.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- 外部-本地tdt -->
<!DOCTYPE doctors SYSTEM "doctor.dtd">

<!--内部dtd-->
<!--<!DOCTYPE doctors [-->
<!--    <!ELEMENT doctors (doctor*) >-->
<!--    <!ELEMENT doctor (name,age,sex) >-->
<!--    <!ELEMENT name (#PCDATA)>-->
<!--    <!ELEMENT age (#PCDATA)>-->
<!--    <!ELEMENT sex (#PCDATA)>-->
<!--    <!ATTLIST doctor id ID #REQUIRED>-->
<!--]>-->

<doctors>
    <doctor id="agger001">
        <name>医生A</name>
        <age>32</age>
        <sex>male</sex>
    </doctor>
    <doctor id="agger002">
        <name>医生A</name>
        <age>32</age>
        <sex>male</sex>
    </doctor>
</doctors>
